#!/usr/bin/env bash
set -euo pipefail
echo "Adding PWA manifest id field for TWA/Play Store install identity..."
mkdir -p public
base64 -d > public/manifest.json << 'B64EOF_manifest'
ewogICJpZCI6ICIvIiwKICAibmFtZSI6ICJTeW1wbHkg4oCUIFN5bXB0b20gVHJhY2tlciIsCiAgInNob3J0X25hbWUiOiAiU3lt
cGx5IiwKICAiZGVzY3JpcHRpb24iOiAiVHJhY2sgc3ltcHRvbXMsIGRpc2NvdmVyIHBhdHRlcm5zLCBhbmQgYnJpbmcgZXZpZGVu
Y2UgdG8geW91ciBkb2N0b3IuIiwKICAic3RhcnRfdXJsIjogIi8iLAogICJkaXNwbGF5IjogInN0YW5kYWxvbmUiLAogICJiYWNr
Z3JvdW5kX2NvbG9yIjogIiNmYWY1ZmYiLAogICJ0aGVtZV9jb2xvciI6ICIjN2MzYWVkIiwKICAib3JpZW50YXRpb24iOiAicG9y
dHJhaXQiLAogICJjYXRlZ29yaWVzIjogWyJoZWFsdGgiLCAibWVkaWNhbCJdLAogICJpY29ucyI6IFsKICAgIHsKICAgICAgInNy
YyI6ICIvaWNvbi0xOTIucG5nIiwKICAgICAgInNpemVzIjogIjE5MngxOTIiLAogICAgICAidHlwZSI6ICJpbWFnZS9wbmciLAog
ICAgICAicHVycG9zZSI6ICJhbnkgbWFza2FibGUiCiAgICB9LAogICAgewogICAgICAic3JjIjogIi9pY29uLTUxMi5wbmciLAog
ICAgICAic2l6ZXMiOiAiNTEyeDUxMiIsCiAgICAgICJ0eXBlIjogImltYWdlL3BuZyIsCiAgICAgICJwdXJwb3NlIjogImFueSBt
YXNrYWJsZSIKICAgIH0KICBdLAogICJzaG9ydGN1dHMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogIkNoZWNrIEluIFRvZGF5IiwK
ICAgICAgInNob3J0X25hbWUiOiAiQ2hlY2sgSW4iLAogICAgICAiZGVzY3JpcHRpb24iOiAiTG9nIHRvZGF5J3Mgc3ltcHRvbXMi
LAogICAgICAidXJsIjogIi8iLAogICAgICAiaWNvbnMiOiBbeyAic3JjIjogIi9pY29uLTE5Mi5wbmciLCAic2l6ZXMiOiAiMTky
eDE5MiIgfV0KICAgIH0KICBdCn0K
B64EOF_manifest
echo "  wrote public/manifest.json"
echo "Done."